=begin
#Google Firebase Cloud Messaging REST API

#Using the Firebase Admin SDK or FCM app server protocols, you can build message requests and send them to targets. 

OpenAPI spec version: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

module FcmClient
  VERSION = '1.0.0'
end
