=begin
#Google Firebase Cloud Messaging REST API

#Using the Firebase Admin SDK or FCM app server protocols, you can build message requests and send them to targets. 

OpenAPI spec version: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for FcmClient::MessagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MessagesApi' do
  before do
    # run before each test
    @instance = FcmClient::MessagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessagesApi' do
    it 'should create an instance of MessagesApi' do
      expect(@instance).to be_instance_of(FcmClient::MessagesApi)
    end
  end

  # unit tests for v1_projects_project_id_messagessend_post
  # Send messages to topics
  # To send messages to topics, specify the desired topic name in the send request. 
  # @param project_id A valid GCP project ID.
  # @param inline_object 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'v1_projects_project_id_messagessend_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
