=begin
#Google Firebase Cloud Messaging REST API

#Using the Firebase Admin SDK or FCM app server protocols, you can build message requests and send them to targets. 

OpenAPI spec version: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

# Common files
require 'fcm_client/api_client'
require 'fcm_client/api_error'
require 'fcm_client/version'
require 'fcm_client/configuration'

# Models
require 'fcm_client/models/inline_object'
require 'fcm_client/models/inline_response200'
require 'fcm_client/models/message'
require 'fcm_client/models/notification'
require 'fcm_client/models/webpush'

# APIs
require 'fcm_client/api/messages_api'

module FcmClient
  class << self
    # Customize default settings for the SDK using block.
    #   FcmClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
